version: '3'

services:
  backend_server:
    container_name: pt_easy_server
    restart: always
    build: ./PTEasy-backend
    ports:
      - "8999:8999"
    command: gunicorn main:app --bind 0.0.0.0:8999 --access-logfile -

